import "./globals.css";
import Navbar from "@/components/Navbar";
import 'bootstrap/dist/css/bootstrap.min.css'
import { montserrat } from "./font";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/litera/"/>
      </head>
      <body className={`${montserrat.className} antialiased`}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
