import "./globals.css";
import Navbar from "@/components/Navbar";
import "bootstrap/dist/css/bootstrap.min.css";
import { montserrat } from "./font";
import Footer from "../components/Footer";
import ThemeContextProvider, { ThemeContext } from "./context/ThemeContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
        style={{ background: "var(--color-secondary)" }}
      >
        <ThemeContextProvider>
          <>
            <Navbar />
            <div className="container pt-4">{children}</div>
            <Footer />
          </>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
